### ISSUE TITLE
GPG verification make build fail

### ISSUE THREAD

**Issue by AntoineMary** [dmgnx/docker-nginx-naxsi#2]
On some build the gpg verification fail and so the build.
It failed your last automated builds :
- https://hub.docker.com/r/dmgnx/nginx-naxsi/builds/b95ly4fnatmvkhssm5qbqxy/
- https://hub.docker.com/r/dmgnx/nginx-naxsi/builds/bhexsyquspr46yphofxxuvc/
- https://hub.docker.com/r/dmgnx/nginx-naxsi/builds/bjad79yyegh6f7ybwqbdhib/

Same error each time : `gpg: keyserver receive failed: Address not available`

**Comment by arcticf0x64** [comment]
The issue seems to rely on sks-keyservers availability.
